### ISSUE TITLE
Papers to add

### ISSUE THREAD

**Issue by samth** [nuprl/gtp.github.io#5]
* Sounds Gradual Typing, Only mostly dead: Bauman et al, OOPSLA 2017
* Theorems for Free for Free: Parametricity, With and Without Types: Ahmed et al, ICFP 2017

**Comment by bennn** [comment]
https://github.com/nuprl/gtp/commit/168e6584a5c18866a13fe2ae4c4a520ba67e4c0d#diff-40b55ea3595955a884c0bfca482ecfafR84
